name: mandangon
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajustado para mayor compatibilidad

dependencies:
  flutter:
    sdk: flutter

  # Íconos estilo iOS
  cupertino_icons: ^1.0.8

  # Para seleccionar imágenes desde la galería o la cámara
  image_picker: ^1.0.7

  # Para enviar la imagen al servidor
  http: ^0.13.6

  # Agrega aquí otras dependencias necesarias

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter para buenas prácticas en Dart
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Si usas imágenes en assets
  assets:
    - assets/images/avatar.png

  
