name: mandangon
description: A new Flutter project

publish_to: 'none' # Eliminar esta línea si no deseas que el proyecto se publique

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias que necesitas
  http: ^1.3.0      # Para hacer solicitudes HTTP
  xml: ^5.3.1
  cupertino_icons: ^1.0.2  # Iconos de Cupertino, si los usas

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Las imágenes y recursos que estás utilizando en el proyecto
  assets:
    - assets/images/logo.png  # Asegúrate de que esta ruta sea correcta
    # Puedes agregar más imágenes o recursos aquí si los tienes

  # Si necesitas fuentes personalizadas, puedes agregar algo como:
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Bold.ttf
  #         weight: 700

