name: mandangon
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  font_awesome_flutter: ^10.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fondo1.png
    - assets/fondo2.png
    - assets/fondo3.png

    - assets/icon_whatsapp.png


