name: mandangon
<<<<<<< HEAD
description: "A new Flutter project."

publish_to: 'none'

=======
description: A new Flutter project

publish_to: 'none' # Eliminar esta línea si no deseas que el proyecto se publique

>>>>>>> origin/main
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  flutter_colorpicker: ^1.0.3
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4
  firebase_auth: ^5.5.1



=======

  # Dependencias que necesitas
  http: ^1.3.0      # Para hacer solicitudes HTTP
  xml: ^5.3.1
  cupertino_icons: ^1.0.2  # Iconos de Cupertino, si los usas
>>>>>>> origin/main

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^5.0.0
=======
>>>>>>> origin/main

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fondo1.png
    - assets/fondo2.png
    - assets/fondo3.png

<<<<<<< HEAD
    - assets/icon_whatsapp.png

=======
  # Las imágenes y recursos que estás utilizando en el proyecto
  assets:
    - assets/images/logo.png  # Asegúrate de que esta ruta sea correcta
    # Puedes agregar más imágenes o recursos aquí si los tienes

  # Si necesitas fuentes personalizadas, puedes agregar algo como:
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Bold.ttf
  #         weight: 700
>>>>>>> origin/main

